[package]
name = "actix-ws"
description = "Websockets for the Actix runtime, without Actors"
version = "0.1.0-alpha.1"
authors = ["asonix <asonix@asonix.dog>"]
readme = "README.md"
repository = "https://git.asonix.dog/asonix/actix-actorless-websockets"
license = "MIT/Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "examples/chat"
]

[dependencies]
actix-http = "2"
actix-rt = "1"
actix-web = "3"
anyhow = "1"
bytes = "0.5"
futures = "0.3"
pin-project = "0.4"
thiserror = "1"
tokio = { version = "0.2", features = ["sync", "stream", "io-util"] }
tokio-util = { version = "0.3", features = ["codec"] }
